# Generated by Django 4.2.3 on 2023-07-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operating_hours", "0002_alter_operatinghour_lunch_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operatinghour",
            name="lunch_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="operatinghour",
            name="lunch_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
