# Generated by Django 4.2.3 on 2023-07-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='non_reimbursement_subjects',
            field=models.ManyToManyField(null=True, related_name='doctors', to='doctors.nonreimbursementdepartment'),
        ),
    ]
