# Generated by Django 4.2.3 on 2023-07-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_non_reimbursement_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(max_length=150)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('lunch_start', models.TimeField()),
                ('lunch_end', models.TimeField()),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operatinghours', to='doctors.doctor')),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
