# Generated by Django 4.2.3 on 2023-07-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_operatinghour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatinghour',
            options={'verbose_name_plural': 'OperatingHours'},
        ),
        migrations.AlterField(
            model_name='operatinghour',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20),
        ),
    ]
