# Generated by Django 4.2.3 on 2023-07-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_operatinghour_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatinghour',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
